// alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

//autenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
export const SELECCIONAR_MODULO = 'SELECCIONAR_MODULO'
export const ERROR_CERRAR_SESION = 'ERROR_CERRAR_SESION'

//barra
export const MOSTRAR_BARRA = 'MOSTRAR_BARRA'
export const OCULTAR_BARRA = 'OCULTAR_BARRA'
export const CAMBIAR_MENU = 'CAMBIAR_MENU'

//anticipoObra
export const CONSULTAR_INFORMACION = 'CONSULTAR_INFORMACION'
export const CONSULTAR_ERROR = 'CONSULTAR_ERROR'
export const SUBMIT_FACTURA = 'SUBMIT_FACTURA'
export const ERROR_REGISTRO_FACTURA = 'ERROR_REGISTRO_FACTURA'
export const SELECC_OBRA_ANTICIPO = 'SELECC_OBRA_ANTICIPO'

//registroObra
export const INFO_GENERAL = 'INFO_GENERAL'
export const ERROR_REGISTRO_OBRA = 'ERROR_REGISTRO_OBRA'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const HANDLE_CHANGE_FECHA = 'HANDLE_CHANGE_FECHA'
export const CARGAR_CONCEPTOS = 'CARGAR_CONCEPTOS'
export const CAMBIAR_ESTADO = 'CAMBIAR_ESTADO'
export const CREAR_OBRA = 'CREAR_OBRA'

//modal
export const ESTADO_MODAL = 'ESTADO_MODAL'
export const REALIZAR_PETICION = 'REALIZAR_PETICION'

//obras
export const ERROR_CARGAR_OBRAS = 'ERROR_CARGAR_OBRAS'
export const CARGAR_OBRAS = 'CARGAR_OBRAS'
export const CARGAR_CONTRATOS = 'CARGAR_CONTRATOS'
export const ERROR_CARGAR_CONTRATOS = 'ERROR_CARGAR_CONTRATOS'

//datosCliente
export const SELECCIONAR_OBRA = 'SELECCIONAR_OBRA'
export const DATOS_PERSONALES = 'DATOS_PERSONALES'
export const DATOS_FISCALES = 'DATOS_FISCALES'
export const DATOS_BANCARIOS = 'DATOS_BANCARIOS'
export const SUBMIT_CLIENTE = 'SUBMIT_CLIENTE'
export const ERROR_REGISTRO_CLIENTE = 'ERROR_REGISTRO_CLIENTE'

//obrasCreadas
export const CAMBIAR_OPCION = 'CAMBIAR_OPCION'
export const FILTRO_OBRAS = 'FILTRO_OBRAS'

//contratoObras
export const CAMBIAR_OPCION_CONTRATO = 'CAMBIAR_OPCION_CONTRATO'
export const SELECT_CONTRATO = 'SELECT_CONTRATO'

//nuevosItems
export const AGREGAR_ITEMS = 'AGREGAR_ITEMS'
export const SUBMIT_ITEMS = 'SUBMIT_ITEMS'
export const ERROR = 'ERROR'