// alerta
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'

//autenticacion
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
export const SELECCIONAR_MODULO = 'SELECCIONAR_MODULO'

//barra
export const MOSTRAR_BARRA = 'MOSTRAR_BARRA'
export const OCULTAR_BARRA = 'OCULTAR_BARRA'

//cargaFactura
export const CONSULTAR_INFORMACION = 'CONSULTAR_INFORMACION'
export const CONSULTAR_ERROR = 'CONSULTAR_ERROR'